import React, { useState, useRef, useEffect } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import AppLayout from "../components/layout/AppLayout";
import { 
  Sparkles, 
  Send, 
  Bot, 
  User, 
  Terminal, 
  Cpu, 
  DollarSign, 
  ShieldAlert, 
  RefreshCw, 
  PlusCircle, 
  AlertTriangle,
  MessageSquare
} from "lucide-react";
import Markdown from "react-markdown";

interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
}

export default function AiAssistant() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [activeSection, setActiveSection] = useState<string>("ai-assistant");
  const [selectedCluster, setSelectedCluster] = useState<string>("gke-core-prod-01");
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "welcome",
      role: "assistant",
      content: "### Welcome to the SmartCluster Autonomous AI SRE Desk\n\nI am your **AI Principal SRE Advisor**, wired into live cluster telemetry, active Prometheus scraping loops, and predicted ML workload models.\n\nAsk me anything about cluster status, CPU/Memory bottlenecks, autoscaling recommendations, or resource allocation optimizations. I can also generate actionable **Kubernetes YAML patches** for immediate deployment.",
      timestamp: new Date()
    }
  ]);
  const [inputMessage, setInputMessage] = useState<string>("");
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const messagesEndRef = useRef<HTMLDivElement | null>(null);

  // Quick Action SRE Suggestions
  const quickActions = [
    { 
      label: "Diagnose Anomalies", 
      prompt: "Perform a system telemetry scan. Are there any active bottlenecks, memory leaks, or cluster anomalies?", 
      icon: ShieldAlert,
      color: "border-cyber-red/30 hover:border-cyber-red text-cyber-red" 
    },
    { 
      label: "Optimize GKE Costs", 
      prompt: "Analyze our cluster nodes configuration and tell me how we can reduce monthly spending. Provide recommendations.", 
      icon: DollarSign,
      color: "border-cyber-green/30 hover:border-cyber-green text-cyber-green" 
    },
    { 
      label: "Get HPA Scaling YAML", 
      prompt: "Provide a Kubernetes HorizontalPodAutoscaler YAML patch to scale our payment-service proactively based on predicted workload peaks.", 
      icon: Cpu,
      color: "border-cyber-purple/30 hover:border-cyber-purple text-[#a78bfa]" 
    },
    { 
      label: "Review Node Limits", 
      prompt: "What are our node allocation limits, and do you recommend configuring any LimitRanges or Quotas?", 
      icon: Terminal,
      color: "border-cyber-cyan/30 hover:border-cyber-cyan text-cyber-cyan" 
    }
  ];

  // Auto-scroll to latest messages
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isLoading]);

  // Handle section transition via URL Search Params or Sidebar
  const handleActiveSectionChange = (section: string) => {
    if (section !== "ai-assistant") {
      navigate(`/dashboard?section=${section}`);
    } else {
      setActiveSection(section);
    }
  };

  const handleSendMessage = async (textToSend: string) => {
    if (!textToSend.trim() || isLoading) return;

    const userMsgId = `user-${Date.now()}`;
    const userMsg: Message = {
      id: userMsgId,
      role: "user",
      content: textToSend,
      timestamp: new Date()
    };

    setMessages(prev => [...prev, userMsg]);
    setInputMessage("");
    setIsLoading(true);

    try {
      const chatHistory = [...messages, userMsg].map(m => ({
        role: m.role,
        content: m.content
      }));

      const response = await fetch("/api/ai/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ messages: chatHistory })
      });

      if (!response.ok) {
        throw new Error("SRE Server API communication failure.");
      }

      const data = await response.json();
      
      setMessages(prev => [
        ...prev,
        {
          id: `assistant-${Date.now()}`,
          role: "assistant",
          content: data.response || "No response generated by AI SRE. Please verify system connections.",
          timestamp: new Date()
        }
      ]);
    } catch (error: any) {
      setMessages(prev => [
        ...prev,
        {
          id: `error-${Date.now()}`,
          role: "assistant",
          content: `⚠️ **System Connection Interruption**: ${error?.message || "Failed to contact the backend AI reasoning engine. Please ensure the dev server is active and port 3000 is open."}`,
          timestamp: new Date()
        }
      ]);
    } finally {
      setIsLoading(false);
    }
  };

  const clearChat = () => {
    setMessages([
      {
        id: "welcome",
        role: "assistant",
        content: "### Welcome to the SmartCluster Autonomous AI SRE Desk\n\nConversation log flushed. Please issue a new diagnostic request, cost audit query, or ask for a Kubernetes configuration patch.",
        timestamp: new Date()
      }
    ]);
  };

  return (
    <AppLayout
      activeSection={activeSection}
      setActiveSection={handleActiveSectionChange}
      selectedCluster={selectedCluster}
      setSelectedCluster={setSelectedCluster}
    >
      <div className="flex flex-col h-[calc(100vh-10rem)] max-w-6xl mx-auto space-y-4">
        
        {/* ASSISTANT PLATFORM HEADER */}
        <div className="flex items-center justify-between p-4 bg-white dark:bg-[#0A0F1F] rounded-2xl border border-slate-200 dark:border-white/5 shadow-sm">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-xl bg-[#8B5CF6]/15 border border-[#8B5CF6]/30 shadow-sm shadow-[#8B5CF6]/10">
              <Sparkles className="w-5 h-5 text-cyber-cyan text-glow-cyan animate-pulse" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-sm font-extrabold text-slate-900 dark:text-white uppercase tracking-wider font-mono">
                  GKE Autonomous AI SRE Advisor
                </h2>
                <span className="text-[9px] bg-cyber-cyan/15 text-cyber-cyan border border-cyber-cyan/30 px-1.5 py-0.2 rounded font-mono font-bold tracking-wider">
                  ACTIVE
                </span>
              </div>
              <p className="text-[10px] text-slate-500 dark:text-slate-400 font-mono mt-0.5">
                Principal-level Gemini telemetry diagnostic & code patch system
              </p>
            </div>
          </div>

          <button 
            onClick={clearChat}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-50 dark:bg-white/5 hover:bg-slate-100 dark:hover:bg-white/10 text-[11px] font-mono font-bold border border-slate-200 dark:border-white/5 rounded-xl text-slate-500 dark:text-slate-400 hover:text-slate-850 transition-all cursor-pointer"
          >
            <PlusCircle className="w-3.5 h-3.5" />
            Flushing Session
          </button>
        </div>

        {/* CHAT VIEWPORT CANVAS */}
        <div className="flex-1 bg-white dark:bg-[#0A0F1F] rounded-2xl border border-slate-200 dark:border-white/5 shadow-sm overflow-hidden flex flex-col">
          
          {/* Scrollable messages history */}
          <div className="flex-1 overflow-y-auto p-6 space-y-6">
            {messages.map((msg) => {
              const isUser = msg.role === "user";
              return (
                <div 
                  key={msg.id} 
                  className={`flex gap-4 ${isUser ? "justify-end" : "justify-start"}`}
                >
                  {/* Assistant Icon */}
                  {!isUser && (
                    <div className="w-8 h-8 rounded-lg bg-cyber-purple/10 border border-cyber-purple/20 flex items-center justify-center shrink-0">
                      <Bot className="w-4.5 h-4.5 text-cyber-purple" />
                    </div>
                  )}

                  {/* Bubble content */}
                  <div className={`max-w-2xl px-5 py-4 rounded-2xl border transition-all ${
                    isUser 
                      ? "bg-slate-100 dark:bg-[#111827]/75 text-slate-800 dark:text-slate-200 border-slate-250 dark:border-white/10 rounded-tr-none font-sans text-xs tracking-wide shadow-sm"
                      : "bg-[#0A0F1F] dark:bg-[#050816]/60 text-slate-800 dark:text-slate-100 border-slate-200 dark:border-cyber-purple/25 rounded-tl-none font-sans text-xs leading-relaxed shadow-sm dark:purple-glow-sm"
                  }`}>
                    <div className="markdown-body">
                      <Markdown>{msg.content}</Markdown>
                    </div>
                    
                    {/* Time indicator */}
                    <span className="text-[8px] font-mono text-slate-400 dark:text-slate-500 block text-right mt-2">
                      {msg.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </span>
                  </div>

                  {/* User Icon */}
                  {isUser && (
                    <div className="w-8 h-8 rounded-lg bg-cyber-cyan/15 border border-cyber-cyan/20 flex items-center justify-center shrink-0">
                      <User className="w-4.5 h-4.5 text-cyber-cyan" />
                    </div>
                  )}
                </div>
              );
            })}

            {/* Thinking / Loader indicator */}
            {isLoading && (
              <div className="flex gap-4 justify-start items-center">
                <div className="w-8 h-8 rounded-lg bg-cyber-purple/10 border border-cyber-purple/20 flex items-center justify-center">
                  <Bot className="w-4.5 h-4.5 text-cyber-purple animate-bounce" />
                </div>
                <div className="px-4 py-3 bg-[#0A0F1F] dark:bg-[#050816]/60 border border-cyber-purple/15 rounded-2xl rounded-tl-none font-mono text-[10px] text-cyber-cyan flex items-center gap-2">
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                  <span>SRE_GEMINI_AI_REASONING_INGESTION_IN_PROGRESS...</span>
                </div>
              </div>
            )}
            
            <div ref={messagesEndRef} />
          </div>

          {/* Quick Actions Suggestions Bar */}
          <div className="px-6 py-3 border-t border-slate-200 dark:border-white/5 bg-slate-50/50 dark:bg-[#050816]/20">
            <span className="text-[9px] font-mono font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500 block mb-2">
              SRE Quick-Action Ingest Triggers
            </span>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-2.5">
              {quickActions.map((act, idx) => {
                const ActIcon = act.icon;
                return (
                  <button
                    key={idx}
                    onClick={() => handleSendMessage(act.prompt)}
                    className={`flex items-center gap-2 p-2 bg-white dark:bg-[#0A0F1F] hover:bg-slate-50 dark:hover:bg-white/5 border rounded-xl text-left transition-all group cursor-pointer text-xs`}
                  >
                    <ActIcon className={`w-4 h-4 shrink-0 ${act.color}`} />
                    <span className="text-[10px] font-mono font-bold truncate text-slate-600 dark:text-slate-350 group-hover:text-slate-850 dark:group-hover:text-white">
                      {act.label}
                    </span>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Bottom Chat Inputs bar */}
          <div className="p-4 border-t border-slate-200 dark:border-white/5 bg-slate-50 dark:bg-[#050816]/40">
            <form 
              onSubmit={(e) => {
                e.preventDefault();
                handleSendMessage(inputMessage);
              }}
              className="flex gap-3 relative"
            >
              <input
                type="text"
                value={inputMessage}
                onChange={(e) => setInputMessage(e.target.value)}
                placeholder="Ask the SRE AI: e.g., 'Is there any CPU pressure?' or 'Scale payment deployment...'"
                className="flex-1 bg-white dark:bg-[#050816] rounded-xl border border-slate-250 dark:border-white/10 px-4 py-3 text-xs focus:outline-none focus:ring-1 focus:ring-cyber-cyan text-slate-850 dark:text-slate-100 placeholder-slate-400 font-sans tracking-wide"
                disabled={isLoading}
              />
              <button
                type="submit"
                className="px-4 bg-[#8B5CF6] hover:bg-opacity-90 text-white rounded-xl flex items-center justify-center transition-all cursor-pointer shadow-md shadow-purple-500/10 active:scale-95 disabled:opacity-50"
                disabled={isLoading || !inputMessage.trim()}
              >
                <Send className="w-4 h-4" />
              </button>
            </form>
          </div>

        </div>

      </div>
    </AppLayout>
  );
}
