apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: smartcluster
  labels:
    app: payment-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: payment-service
  type: ClusterIP
